apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-app
  name: udaconnect-app
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
    nodePort: 30000
  selector:
    service: udaconnect-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-app
  name: udaconnect-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-app
  template:
    metadata:
      labels:
        service: udaconnect-app
    spec:
      containers:
      - image: agilestrategist/udaconnect-app:latest
        name: udaconnect-app
        iimagePullPolicy: Always
        env:
        - name: PERSONS_API_SRV
          valueFrom:
            configMapKeyRef:
              name: fe-env
              key: PERSONS_API_SRV
        - name: CONNECTIONS_API_SRV
          valueFrom:
            configMapKeyRef:
              name: fe-env
              key: CONNECTIONS_API_SRV
        resources:
            requests:
              memory: "128Mi"
              cpu: "64m"
            limits:
              memory: "256Mi"
              cpu: "256m"
      restartPolicy: Always
