openapi: 3.0.0
info:
  description: API for interacting with Persons from UdaConnect application
  version: "1.0.0"
  title: Persons API
paths:
  /persons:
    get:
      summary: Returns all persons
      operationId: getAllPersons
      description: Retrieves all the persons that have been created.
      responses:
        '200':
          description: Successfully retrieved all persons
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonSchema'
        '400':
          description: Bad input parameter
    post:
      summary: Creates a new persons
      operationId: createPerson
      description: Adds a person to the system
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonSchema
        description: Person to add
      responses:
        '201':
          description: Person created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonSchema'
        '400':
          description: 'Invalid input, object invalid'
  /persons/{personId}:
    get:
      summary: Return person by id
      operationId: getPersonById
      description: |
        Returns person by id
      parameters:
        - in: path
          name: personId
          schema:
            type: integer
          required: true
          description: Numeric id of the person to get
      responses:
        '200':
          description: Successfully retrieved a person information with id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonSchema'
        '404':
          description: Requested item ID was not found
components:
  schemas:
    PersonSchema:
      type: object
      required:
        - id
        - first_name
        - last_name
        - company_name
      properties:
        id:
          type: integer
          example: 5
        first_name:
          type: string
          example: James
        last_name:
          type: string
          example: Brenda
        company_name:
          type: string
          example: Amazon